// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzjmakxqdtjkhyznlgds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6am1ha3hxZHRqa2h5em5sZ2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Njk5NTQsImV4cCI6MjA3MzQ0NTk1NH0.Cu3Wcz84AD7dgSsjHHJ3PKFmnhR--GxzhKoDC41tkrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});